### ISSUE TITLE
dynamic og:title angular2

### ISSUE THREAD

**Issue by giaule** [fulls1z3/ngx-meta#14]
Dear support,

When i using browser that very google (show title), but i using share link facebook, this can't read metadata my site.

Please help me,
Thanks.

**Comment by Chuvisco88** [comment]
Hi @giaule 

I understand it that you want to copy your url to Facebook for sharing and don't get the meta.
If this is the case the reason is that Facebook is calling the url and directly reads the meta and does not wait until the meta data is initialised by the module as this happens asynchronously.

Probably the maintainer can you provide with more infos, but regarding the initialisation, the only way would be by server-side rendering the meta data.

**Comment by fulls1z3** [comment]
Hi @giaule 

Thanks for your interest in `ng2-metadata`, and sorry for the late reply.

As mentioned in #4:

> Generated metadata is not **currently** accessible by bots except Google crawler. For now, the only method to generate meta tags at the server-side in order to be crawl-able by bots such as facebook.
> 
> However, I'm keeping track of developments with those crawlers/bots and will publish updates as things become available.

As @Chuvisco88 said, currently it seems possible thru server-side rendering.

**Comment by giaule** [comment]
Dear support,

So i need to build a server site for this function.

Thanks support.
