### ISSUE TITLE
where are old versions

### ISSUE THREAD

**Issue by UrosSimovic** [fulls1z3/ngx-meta#38]
Which commit number was version 0.2 rc4. This version worked just fine for me, with 0.4rc1 I have problem with AoT compilation and lodash. It is a bad practice to unpublish old versions from npm.

**Comment by fulls1z3** [comment]
Hi @UrosSimovic I think you're using Angular 2, and that's why you're facing problems with `v0.4.0-rc.1` which is scaled to Angular 4.

You can use the `v0.2.0-rc.5` by specifying it in your `package.json`, it contains all the functionality that `v0.2.0-rc.4` had, with issues resolved.

**Comment by UrosSimovic** [comment]
Thanks for your answer. I'm using angular `v4.0.1`, but there are some problem with lodash. I'm using [https://github.com/mgechev/angular-seed](https://github.com/mgechev/angular-seed) for aot building and rollup. There is probably problem with angular-seed, but while resolving problem I need `v0.2.0-rc-4` which was the last version without lodash.

Would you please return old version to npm?

**Comment by fulls1z3** [comment]
Hi @UrosSimovic, not with `lodash` but with `@types/lodash` there are many problems - especially on versions higher than `4.14.55` and lower than `4.14.50`. It's all related with TypeScript 2.0 / 2.1 / 2.2. When the version is fixed to `4.14.55` (*instead of `^4.14.55` or higher or lower*) it might help disappearing those problems (*using TypeScript 2.2*).

Well this was just some little advice, anyway I'm attaching the bundle of `v0.2.0-rc.4` below this post, just copy it to the `node_modules` foler.

Hope it helps, and if you need further help with `lodash`, just let me know.

[meta.zip](https://github.com/nglibs/meta/files/915822/meta.zip)

**Comment by UrosSimovic** [comment]
Thanks for meta.zip.

As as I thought there is problem with lodash and rollup. A lot of similiar issues regarding angular, rollup and lodash. 

I can't see any advanteges of using lodash just for two methods (has, get). It is easy to replace them.

**Comment by fulls1z3** [comment]
Actually I want to thank you @UrosSimovic for this feedback, I'm considering them all before reaching the final release (*from the RC's*).

At the next RC, I'll remove the lodash dependency and I think after that RC `meta` will reach to the final release.

**Comment by UrosSimovic** [comment]
Oh, nice. Thanks again.

**Comment by fulls1z3** [comment]
I've just created an issue about this, so you can track the status on #40.
