### ISSUE TITLE
rename to `@ngx-meta/core`

### ISSUE THREAD

**Issue by fulls1z3** [fulls1z3/ngx-meta#43]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => check the README and search github for a similar issue or PR before submitting
[ ] support request => check the README and search github for a similar issue or PR before submitting
[X] feature request
```

**Current behavior**

**Expected/desired behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by brentchow** [comment]
Docs should be updated to show that this is the new home for `@nglibs/meta`. There should also be some sort of note left at the old repo URL that `@nglibs/meta` was deprecated and where to find the renamed version.

This was a big bitch when all the sudden builds started breaking. A heads up would have been nice. Otherwise, thanks for building/maintaining this.

**Comment by fulls1z3** [comment]
@brentchow a few days ago I contacted npm about the deprecation for a few packages and moving them under `npm` scope, but seems like `@nglibs` is not deprecated but removed. I'll see what can I do for this.

Also, thanks for notifying 👍
