### ISSUE TITLE
source metadata not changing ?

### ISSUE THREAD

**Issue by BenoitBruy** [fulls1z3/ngx-meta#5]
Hi,

I've just installed the ng2-metadata package really easily. 
Thanks for your work !

I checked the metadata in my head element and everything is fine. 
The problem is in my source code, the metadata are the default one..

It is an expected behaviour ?

**Comment by fulls1z3** [comment]
Hi @BenoitBruy,

Thanks for your interest in `ng2-metadata`.

Actually the information you provided is quite limited, but if I understood correctly you're checking the changes on both **view page source** and **developer tools/console**.

`ng2-metadata` does not change source, it manipulates the head elements during runtime. I think that's the reason why you're not seeing changes in the source but in the developer console - so that I can say that's the expected behavior.

Please don't hesitate to post for further details.

**Comment by BenoitBruy** [comment]
Thanks for your answer @fulls1z3 

Yeah this is exactly what I mean.

Do you know how to change the balise in the source code by the way ? 

Because, this is the aim of editing metada dynamically, isn't it ? 
When I share something from my website, anything is dynamic..
