### ISSUE TITLE
warning found 

### ISSUE THREAD

**Issue by BenoitBruy** [fulls1z3/ngx-meta#6]
Hi again ! 

I'm using the MetadataStaticLoader.

```
function createMetadataLoader() {
    return new MetadataStaticLoader({
        pageTitlePositioning: PageTitlePositioning.AppendPageTitle,
        pageTitleSeparator: '',
        applicationName: '',
        defaults: {
            title: 'Toto'
        }
    });
}
```

I've got this warning in my angular 2 webpack app with ng2-metadata. Do I have miss something ?
I'm in dev mod.

```
/src/app/app.module.ts
56:30 export 'PageTitlePositioning' was not found in 'ng2-metadata'
Error: export 'PageTitlePositioning' was not found in 'ng2-metadata'
```

**Comment by fulls1z3** [comment]
Hi again, PageTitlePositioning should be imported together with MetadataStaticLoader, MetadataLoader and MetadataModule.

Also, can you please post your source code here (better via plunkr), so that I can have some in-depth analysis?

**Comment by BenoitBruy** [comment]
This has been imported.

`import {MetadataModule, MetadataStaticLoader, PageTitlePositioning, MetadataLoader} from 'ng2-metadata';`

![image](https://cloud.githubusercontent.com/assets/16610931/21146278/694ac32e-c151-11e6-86e3-186e92937a29.png)

**Comment by fulls1z3** [comment]
In this case I need more details related to your app. Can you please tell me what is the webpack, and angular version that you're trying to compile the app with?

And also, I'll need you to provide the part your source code via plunkr.

**Comment by BenoitBruy** [comment]
We are using angular 2.1.0. And webpack 2.1.0-beta22.

Regards

**Comment by fulls1z3** [comment]
Can you please post me your typescript version, and contents of tsconfig.json?

**Comment by BenoitBruy** [comment]
Sure Typescript 2.0.3.

Here is tsconfig.json:

`{
    "compileOnSave": false,
    "buildOnSave": false,
    "atom": { "rewriteTsconfig": false },
    "compilerOptions": {
        "declaration": false,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "mapRoot": "/",
        "module": "es2015",
        "moduleResolution": "node",
        "noEmitOnError": true,
        "noImplicitAny": false,
        "outDir": "../dist/",
        "rootDir": ".",
        "sourceMap": true,
        "target": "es5",
        "inlineSources": true,
        "types": [
            "core-js",
            "hammerjs",
            "node",
            "source-map",
            "uglify-js",
            "webpack",
            "facebook-js-sdk",
            "fullcalendar",
            "google-apps-script",
            "google-libphonenumber",
            "googlemaps",
            "jquery",
            "lodash",
            "material-design-lite",
            "moment",
            "ng2-pagination"
        ]
    },
    "exclude": [
        "node_modules",
        "dist"
    ],
    "awesomeTypescriptLoaderOptions": {
        "forkChecker": true,
        "useWebpackText": true
    }
}
`

**Comment by fulls1z3** [comment]
Ok, thanks for your immediate feedback.

According to your environment and ts config, It's difficult to say it might happen because of environment configuration.

Here we have **Visual Studio 2015 (Update 3)** and use **TS 2.0.10**, **@angular 2.2.4**, **webpack 2.1.0-beta27** and **awesome-typescript-loader 3.0.0-beta.17**; but it was even possible to get this package running with lower **@angular** and **ts** versions (and also using **systemjs** instead of webpack).

I double checked our development environment and was able to get see the `PageTitlePositioning` object on the IDE intellisense.

![sss](https://cloud.githubusercontent.com/assets/19705684/21260089/1517b53a-c38d-11e6-8332-0f85997ad4fe.png)

Also, unit tests on our development environment, [travis-ci](https://travis-ci.org/fulls1z3/ng2-metadata) and [appveyor](https://ci.appveyor.com/project/fulls1z3/ng2-metadata) have been passed without errors. Please keep in mind that, we use different `PageTitlePositioning` values to run tests.

I would suggest you to clean ng2-metadata in your node_modules folder and update the packages again. If it does not help, try to use this package on a fresh project (you can use any of seed projects such as [angular-seed](https://github.com/angular/angular-seed) or [angular-seed-advanced](https://github.com/NathanWalker/angular-seed-advanced)).

**Comment by BenoitBruy** [comment]
Thanks for your answer ! 

I've got as well the prediction in my IDE JetBrains. That's why, it is running basically, just got a warning in dev mode..

Maybe, updating our package will fix the issue.

I'll keep you up to date.

Thanks.
