### ISSUE TITLE
Question about this project in relation to nglibs/meta

### ISSUE THREAD

**Issue by deathbearbrown** [fulls1z3/ngx-meta#99]
**I'm submitting a ...**  (check one with "x")
```
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  <!-- Please check the repository for a similar issue or PR before submitting -->
[ ] Support request => <!-- Please check the repository for a similar issue or PR before submitting -->
[ ] Feature request
[ ] Documentation issue or request
[x] Question
```

**Current behavior**
I am working on a project which is new to me that has https://www.npmjs.com/package/@nglibs/meta as a dependency. A teammate noticed this morning that it no longer exists.  Since @fulls1z3 is the creator of the nglibs project, I was wondering if this is an entirely new project or the nglibs project renamed.

**Comment by fulls1z3** [comment]
Just renaming, not totally entirely a new project.

The background of this problem is that I contacted npm to deprecate it along with several other packages but resulted as a deletion by a misunderstanding I think.

Anyway, you can straightforwardly use **ngx-meta** and simply place a *MetaGuard* on your routes rather than including it in your *AppComponent*. The rest works the same.

Meanwhile, if you're still on Angular 2 (*which I really don't recommend*), use the `v2.0.1`. Otherwise `v4.0.1` is fine for you.
